services:
  core_service:
    build:
      context: .
      dockerfile: infra/dockerfiles/core.Dockerfile
    image: core-${MODE}:${TAG}
    container_name: core_${MODE}
    depends_on:
      model_service:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./configs/core_config.yaml:/app/config.yaml
      - ./infra/migrations:/app/migrations
    ports:
      - "${CORE_EXPORT}:8080"
    environment:
      MODE: ${MODE}
      CONFIG_PATH: ./config.yaml
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_BASE: ${PG_BASE}
      PG_USER: ${PG_USER}
      PG_PSWD: ${PG_PSWD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      ML_HOST: ${ML_HOST}
      ML_PORT: ${ML_PORT}
      JWT_SECRET: ${JWT_SECRET}
      VK_TOKEN: ${VK_TOKEN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    networks:
      - service-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  tg_service:
    build:
      context: .
      dockerfile: infra/dockerfiles/tg.Dockerfile
    image: tg-${MODE}:${TAG}
    container_name: tg_${MODE}
    depends_on:
      core_service:
        condition: service_healthy
    volumes:
      - ./configs/tg_config.yaml:/app/config.yaml
    ports:
      - "${TG_EXPORT}:8080"
    environment:
      MODE: ${MODE}
      CONFIG_PATH: ./config.yaml
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      CORE_HOST: ${CORE_HOST}
      CORE_PORT: ${CORE_PORT}
    networks:
      - service-net
    healthcheck:
      disable: true
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  vk_service:
    build:
      context: .
      dockerfile: infra/dockerfiles/vk.Dockerfile
    image: vk-${MODE}:${TAG}
    container_name: vk_${MODE}
    depends_on:
      core_service:
        condition: service_healthy
    volumes:
      - ./configs/vk_config.yaml:/app/config.yaml
    ports:
      - "${VK_EXPORT}:8080"
    environment:
      MODE: ${MODE}
      CONFIG_PATH: ./config.yaml
      VK_TOKEN: ${VK_TOKEN}
      CORE_HOST: ${CORE_HOST}
      CORE_PORT: ${CORE_PORT}
    networks:
      - service-net
    healthcheck:
      disable: true
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  model_service:
    build:
      context: ./ml
      dockerfile: ./../infra/dockerfiles/ml.Dockerfile
    image: model-${MODE}:${TAG}
    container_name: model_${MODE}
    volumes:
      - ${MODEL_FILE}:/app/model.pt
    environment:
      MODE: ${MODE}
    networks:
      - service-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:17
    container_name: postgres_sb_${MODE}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSWD}
      POSTGRES_DB: ${PG_BASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_BASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8-alpine
    container_name: redis_sb_${MODE}
    networks:
      - service-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  adminer:
    image: adminer:latest
    container_name: adminer_sb_${MODE}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${AD_EXPORT}:8080"
    networks:
      - service-net

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter_${MODE}
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - service-net

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus_${MODE}
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
    networks:
      - service-net

  # Grafana
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana_${MODE}
    ports:
      - "${GF_EXPORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_SIGNUP}
    volumes:
      - ./infra/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - service-net

volumes:
  postgres_data:
    name: postgres_${MODE}_data
  prometheus_data:
    name: prometheus_${MODE}_data
  grafana_data:
    name: grafana_${MODE}_data

networks:
  service-net:
    name: net-${MODE}
    driver: bridge
