services:
  main_service:
    build:
      context: .
      dockerfile: configs/service.Dockerfile
    image: main-${MODE}:${TAG}
    container_name: main_${MODE}
    depends_on:
      - ml_service
      - postgres
    ports:
      - "${MAIN_PORT}:8080"
    env_file:
      - .env
    networks:
      - service-net

  bot_service:
    build:
      context: .
      dockerfile: configs/bot.Dockerfile
    image: bot-${MODE}:${TAG}
    container_name: bot_${MODE}
    depends_on:
      - main_service
    ports:
      - "${BOT_PORT}:8000"
    env_file:
      - .env
    networks:
      - service-net

  ml_service:
    build:
      context: ./ml
      dockerfile: ./../configs/ml.Dockerfile
    image: model-${MODE}:${TAG}
    container_name: model_${MODE}
    volumes:
      - ./ml/${MODEL_FILE}:/app/best_context_model.pt
    env_file:
      - .env
    networks:
      - service-net

  postgres:
    image: postgres:17
    container_name: postgres_sb_${MODE}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSWD}
      POSTGRES_DB: ${PG_BASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service-net

  adminer:
    image: adminer:latest
    container_name: adminer_sb_${MODE}
    restart: always
    depends_on:
      - postgres
    ports:
      - "${AD_PORT}:8080"
    networks:
      - service-net

volumes:
  postgres_data:
    name: postgres_data

networks:
  service-net:
    name: net-${MODE}
    driver: bridge
