services:
  main_service:
    build:
      context: .
      dockerfile: ./infra/service.Dockerfile
    container_name: main
    ports:
      - "${MAIN_PORT}:8080"
    env_file:
      - .env

  bot_service:
    build:
      context: .
      dockerfile: ./infra/bot.Dockerfile
    container_name: bot
    ports:
      - "${BOT_PORT}:8000"
    env_file:
      - .env

  ml_service:
    build:
      context: ./ml
      dockerfile: ./../infra/ml.Dockerfile
    container_name: model
    ports:
      - "${ML_PORT}:8000"
    volumes:
      - ./ml/${MODEL_FILE}:/app/best_context_model.pt
    env_file:
      - .env

  postgres:
    image: postgres:17
    container_name: postgres_sb
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSWD}
      POSTGRES_DB: ${PG_BASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_vk_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_sb
    restart: always
    ports:
      - "${AD_PORT}:8080"

volumes:
  postgres_vk_data:
