app:
  name: VKBot
  host: 0.0.0.0
  port: 8080
  prefix: /api/v1
  swagger_path: ./data/docs/server.json

  logger:
    level: TRACE

  vk:
    token: VK_TOKEN

  metrics:
    port: 8081

  core_service:
    host: CORE_HOST
    port: CORE_PORT