name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      #      - name: Run linter
      #        run: |
      #          # Установка golangci-lint
      #          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      #          golangci-lint run ./...

#      - name: Run tests
#        run: go test

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    env:
      MODE: ${{ github.ref_name == 'refs/heads/main' && 'prod' || 'test' }}
      BUILD_ENV: ${{ github.ref_name == 'refs/heads/main' && secrets.PROD_ENV || secrets.TEST_ENV }}
      SERVER_CONFIG: ${{ secrets.SSH_CONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare ssh
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Создаем приватный ключ для SSH
          mkdir -p ~/.ssh
          echo -n "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG echo "SSH connection successful"

      - name: Prepare images
        run: |
          TAG="$(cat VERSION)"
          echo "$BUILD_ENV" > .env
          sed -i "s/^MODE=dev$/MODE=$MODE/" .env
          sed -i "s/^TAG=.*$/TAG=$TAG/" .env
          docker compose build core_service bot_service ml_service
          docker save -o all_images.tar model-$MODE:$TAG bot-$MODE:$TAG core-$MODE:$TAG

      - name: Deploy
        env:
          APP_DIR: /home/ubuntu/spambreaker
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG \
            "cd $APP_DIR/$MODE && docker compose down" || echo "Down error"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key all_images.tar \
            $SERVER_CONFIG:$APP_DIR/$MODE || echo "SCP image error"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -r .env docker-compose.yaml ./configs/ \
            $SERVER_CONFIG:$APP_DIR/$MODE/ || echo "SCP configs error"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -r ./infra/migrations/ \
            $SERVER_CONFIG:$APP_DIR/$MODE/infra/ || echo "SCP configs error"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG \
            "docker load -i $APP_DIR/$MODE/all_images.tar" || echo "Image load error"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG \
            "cd $APP_DIR/$MODE && docker compose up -d --force-recreate" || echo "Run error"
          RESULT=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG "docker ps -q | wc --l")
          EXPECT=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $SERVER_CONFIG \
            "cd $APP_DIR/$MODE && docker compose config --services | wc -l")
          if [[ "$RESULT" -eq "$EXPECT" ]]; then
            echo "Success"
          else
            echo "Expected $EXPECT containers, got $RESULT"
            exit 1
          fi
